### ISSUE TITLE
LLama required?

### ISSUE THREAD

**Issue by cvarrichio** [yoheinakajima/babyagi#226] opened 2023-04-21 22:18 UTC
Am I confused, because it seems like Llama is now required.  This is a massive increase in system requirements.  Previously since everything was handled through the APIs, you could run this on a EC2 Micro instance or a work laptop.  Now I'm finding that it's installing CUDA, several gigabytes worth of installs, etc?  I understand why some people would want to use LLama, but shouldn't this clearly be optional?

**Comment by dancingmadkefka** [comment] 2023-04-21 22:34
Ya I don't understand that either tbh

**Comment by micromysore** [comment] 2023-04-22 03:49
The default is still openAI models. ie. Llama is not required, unless you explicitly ask for it in the command line while invoking the babyagi.

**Comment by dancingmadkefka** [comment] 2023-04-22 09:34
the issue is with the *installing* of all that stuff, not that we are forced to use it.

**Comment by cvarrichio** [comment] 2023-04-22 14:55
Absolutely.  Running llama is irrelvant, being forced to install it plus its dependencies is a dealbreaker.

**Comment by francip** [comment] 2023-04-22 21:06
Yeah, my bad. This is now fixed, llama-cpp bindings are in extensions/requirements.txt.

**Closed** 2023-04-22 21:06 UTC
